// Auto-generated by refresh_iran_news.py — do not edit by hand.
// Crypto: CoinGecko simple/price. FX USD/EUR -> IRR: tgju.org (Iran free-market).

export interface CryptoQuote {
  id: string
  symbol: string
  name: string
  priceUsd: number
  change24h: number
}

export interface FxQuote {
  code: 'USD' | 'EUR'
  name: string
  irrPerUnit: number   // 1 USD = X IRR (or 1 EUR = X IRR)
  perIrr: number       // 1 IRR = X USD/EUR (decimal)
  change24h: number    // % change vs previous day (0 if unavailable)
}

export interface MarketsSnapshot {
  fetchedAt: string
  crypto: CryptoQuote[]
  fx: FxQuote[]
}

export const MARKETS: MarketsSnapshot = {
  "fetchedAt": "2026-09-04T12:18:32+03:30",
  "crypto": [
    {
      "id": "bitcoin",
      "symbol": "BTC",
      "name": "Bitcoin",
      "priceUsd": 81077.0,
      "change24h": 4.15
    },
    {
      "id": "ethereum",
      "symbol": "ETH",
      "name": "Ethereum",
      "priceUsd": 2521.71,
      "change24h": 4.83
    }
  ],
  "fx": []
}
